### ISSUE TITLE
[Solved] System.ArgumentException in ApnsConnection.Send()

### ISSUE THREAD

**Issue by IvoryRubble** [IvoryRubble/PushSharp.Core#1]
### Describe your issue:
System.ArgumentException in ApnsConnection.Send() happens sometimes when call `apnsBroker.QueueNotification(apnsNotification);` several thousends times in foreach loop
This happens likely because `ApnsConnection.notifications` Queue is not thread-safe

### Please provide any Exception Stack Traces
```
System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds.
Parameter name: sourceArray
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at PushSharp.Apple.ApnsConnection.Send(CompletableApnsNotification notification)
   at PushSharp.Apple.ApnsServiceConnection.Send(ApnsNotification notification)
```

**Comment by IvoryRubble** [comment]
One suggestion is properly lock `notifications` Queue in ApnsConnection.
https://github.com/Redth/PushSharp/issues/672#issuecomment-336447277
#2

**Comment by IvoryRubble** [comment]
Another solution is replace `notification` Queue to ConcurrentQueue 
https://github.com/Redth/PushSharp/pull/770

**Comment by IvoryRubble** [comment]
Published nuget package with fix for this issue: https://www.nuget.org/packages/Actonica.PushSharp.Core/
This package deploys pull-request #2
